### ISSUE TITLE
Cache stored but nothing is retrieved

### ISSUE THREAD

**Issue by guschiavon** [Mesomorphic/netlify-plugin-jekyll-cache#1]
I've got a Jekyll site deployed on Netlify which uses the `jekyll-webp` plugin. This plugin generates a WebP version of each image in the project `/assets/img` folder and is run during build time, storing the newly-generated `.webp` files in the `_site` folder. 

This consumes significant build minutes (currently at 13 min) and thus the idea of having the `_site/assets/img` folder cached is desired to reduce build minutes. 

I've installed the `netlify-plugin-jekyll-cache` via Netlify UI and configured the `netlify.toml` file as follows:

```
[[plugins]]
  package = "netlify-plugin-jekyll-cache"

	[plugins.inputs]  
	# jekyllSource = "/opt/build/cache"
```

Testing the plugin, I get the following messages on build time:

```
3:52:26 PM: ────────────────────────────────────────────────────────────────
3:52:26 PM:   Netlify Build                                                 
3:52:26 PM: ────────────────────────────────────────────────────────────────
3:52:26 PM: ​
3:52:26 PM: ❯ Version
3:52:26 PM:   @netlify/build 18.17.2
3:52:26 PM: ​
3:52:26 PM: ❯ Flags
3:52:26 PM:   baseRelDir: true
3:52:26 PM:   buildId: 6169cdb9b90472000893123e
3:52:26 PM:   deployId: 6169cdb9b904720008931240
3:52:26 PM: ​
3:52:26 PM: ❯ Current directory
3:52:26 PM:   /opt/build/repo
3:52:26 PM: ​
3:52:26 PM: ❯ Config file
3:52:26 PM:   /opt/build/repo/netlify.toml
3:52:26 PM: ​
3:52:26 PM: ❯ Context
3:52:26 PM:   production
3:52:26 PM: ​
3:52:26 PM: ❯ Loading plugins
3:52:26 PM:    - netlify-plugin-jekyll-cache@1.0.0 from netlify.toml and package.json
3:52:26 PM: ​
3:52:26 PM: ────────────────────────────────────────────────────────────────
3:52:26 PM:   1. netlify-plugin-jekyll-cache (onPreBuild event)             
3:52:26 PM: ────────────────────────────────────────────────────────────────
3:52:26 PM: ​
3:52:28 PM: Restoring Jekyll cache
3:52:28 PM: ​
3:52:28 PM: (netlify-plugin-jekyll-cache onPreBuild completed in 1.7s)
```

Despite, the site continues to be rebuilt every time and the files are being regenerated; is this the correct configuration? Which path should I define for the `jekyllSource` input?

Appreciate your help.

**Comment by typhoon2099** [comment]
Hi @guschiavon. This plugin caches Jekyll's cache directory (`.jekyll-cache`). The `jekyllSource` option is only required if you've changed the source directory for Jekyll, so that it can find this cache file. It doesn't look like `jekyll-webp` uses the Jekyll Cache folder for reducing build times. I've been using [Jekyll Picture Tag](https://github.com/rbuchberger/jekyll_picture_tag), which prompted me to build this Netlify Plugin.

I think caching the `_site` directory (or parts of it) could work, but would require some careful thought, my fear would be that Jekyll either doesn't remove stuff that shouldn't be there, or it removes it as soon as the build starts (I think you'd need the `incremental` flag to keep it in place. For now I would recommend switching to something that makes use of Jekyll's cache directory, or finding a way to implement it in `jekyll-webp`.

**Comment by Agadelic** [comment]
Hi I get this error log readout on netlify from your plugins to gatsby for my linux repo :- 
11:21:07 AM: Build ready to start
11:21:09 AM: build-image version: a6bb34428a07e7de82f4df5dfe1843fbde91f670 (focal)
11:21:09 AM: build-image tag: v4.5.1
11:21:09 AM: buildbot version: 047dc2001d6cf9f76ba77ae34521e2065ab5c2bd
11:21:09 AM: Fetching cached dependencies
11:21:09 AM: Failed to fetch cache, continuing with build
11:21:09 AM: Starting to prepare the repo for build
11:21:10 AM: No cached dependencies found. Cloning fresh repo
11:21:10 AM: git clone git@gitlab.com:Agadelic/Blackstarvirtualmint
11:21:14 AM: Preparing Git Reference refs/heads/master
11:21:16 AM: Parsing package.json dependencies
11:21:17 AM: Starting build script
11:21:17 AM: Installing dependencies
11:21:17 AM: Python version set to 2.7
11:21:18 AM: v16.13.1 is already installed.
11:21:19 AM: Now using node v16.13.1 (npm v8.1.2)
11:21:19 AM: Started restoring cached build plugins
11:21:19 AM: Finished restoring cached build plugins
11:21:19 AM: Attempting ruby version 2.7.2, read from environment
11:21:21 AM: Using ruby version 2.7.2
11:21:21 AM: Using PHP version 8.0
11:21:21 AM: Started restoring cached node modules
11:21:21 AM: Finished restoring cached node modules
11:21:22 AM: Installing NPM modules using NPM version 8.1.2
11:21:23 AM: up to date, audited 1 package in 415ms
11:21:23 AM: found 0 vulnerabilities
11:21:23 AM: NPM modules installed
11:21:24 AM: Started restoring cached composer dependencies
11:21:24 AM: Finished restoring cached composer dependencies
11:21:24 AM: No composer.lock file present. Updating dependencies to latest instead of installing from lock file. See https://getcomposer.org/install for more information.
11:21:24 AM: Loading composer repositories with package information
11:21:25 AM: Updating dependencies
11:21:25 AM: Lock file operations: 74 installs, 0 updates, 0 removals
11:21:25 AM:   - Locking amphp/amp (v2.6.1)
11:21:25 AM:   - Locking amphp/byte-stream (v1.8.1)
11:21:25 AM:   - Locking composer/package-versions-deprecated (1.11.99.4)
11:21:25 AM:   - Locking composer/pcre (1.0.0)
11:21:25 AM:   - Locking composer/semver (3.2.6)
11:21:25 AM:   - Locking composer/xdebug-handler (2.0.3)
11:21:25 AM:   - Locking dnoegel/php-xdg-base-dir (v0.1.1)
11:21:25 AM:   - Locking doctrine/instantiator (1.4.0)
11:21:25 AM:   - Locking felixfbecker/advanced-json-rpc (v3.2.1)
11:21:25 AM:   - Locking felixfbecker/language-server-protocol (1.5.1)
11:21:25 AM:   - Locking guzzlehttp/guzzle (7.4.1)
11:21:25 AM:   - Locking guzzlehttp/promises (1.5.1)
11:21:25 AM:   - Locking guzzlehttp/psr7 (2.1.0)
11:21:25 AM:   - Locking myclabs/deep-copy (1.10.2)
11:21:25 AM:   - Locking netresearch/jsonmapper (v4.0.0)
11:21:25 AM:   - Locking nikic/php-parser (v4.13.2)
11:21:25 AM:   - Locking nimbly/capsule (1.1.2)
11:21:25 AM:   - Locking nimbly/shuttle (0.4)
11:21:25 AM:   - Locking openlss/lib-array2xml (1.0.0)
11:21:25 AM:   - Locking phar-io/manifest (2.0.3)
11:21:25 AM:   - Locking phar-io/version (3.1.0)
11:21:25 AM:   - Locking php-coveralls/php-coveralls (v2.5.2)
11:21:25 AM:   - Locking phpdocumentor/reflection-common (2.2.0)
11:21:25 AM:   - Locking phpdocumentor/reflection-docblock (5.3.0)
11:21:25 AM:   - Locking phpdocumentor/type-resolver (1.5.1)
11:21:25 AM:   - Locking phpspec/prophecy (v1.15.0)
11:21:25 AM:   - Locking phpunit/php-code-coverage (9.2.10)
11:21:25 AM:   - Locking phpunit/php-file-iterator (3.0.6)
11:21:25 AM:   - Locking phpunit/php-invoker (3.1.1)
11:21:25 AM:   - Locking phpunit/php-text-template (2.0.4)
11:21:25 AM:   - Locking phpunit/php-timer (5.0.3)
11:21:25 AM:   - Locking phpunit/phpunit (9.5.10)
11:21:25 AM:   - Locking psr/container (2.0.2)
11:21:25 AM:   - Locking psr/http-client (1.0.1)
11:21:25 AM:   - Locking psr/http-factory (1.0.1)
11:21:25 AM:   - Locking psr/http-message (1.0.1)
11:21:25 AM:   - Locking psr/log (2.0.0)
11:21:25 AM:   - Locking ralouphie/getallheaders (3.0.3)
11:21:25 AM:   - Locking sebastian/cli-parser (1.0.1)
11:21:25 AM:   - Locking sebastian/code-unit (1.0.8)
11:21:25 AM:   - Locking sebastian/code-unit-reverse-lookup (2.0.3)
11:21:25 AM:   - Locking sebastian/comparator (4.0.6)
11:21:25 AM:   - Locking sebastian/complexity (2.0.2)
11:21:25 AM:   - Locking sebastian/diff (4.0.4)
11:21:25 AM:   - Locking sebastian/environment (5.1.3)
11:21:25 AM:   - Locking sebastian/exporter (4.0.4)
11:21:25 AM:   - Locking sebastian/global-state (5.0.3)
11:21:25 AM:   - Locking sebastian/lines-of-code (1.0.3)
11:21:25 AM:   - Locking sebastian/object-enumerator (4.0.4)
11:21:25 AM:   - Locking sebastian/object-reflector (2.0.4)
11:21:25 AM:   - Locking sebastian/recursion-context (4.0.4)
11:21:25 AM:   - Locking sebastian/resource-operations (3.0.3)
11:21:25 AM:   - Locking sebastian/type (2.3.4)
11:21:25 AM:   - Locking sebastian/version (3.0.2)
11:21:25 AM:   - Locking symfony/config (v6.0.0)
11:21:25 AM:   - Locking symfony/console (v6.0.0)
11:21:25 AM:   - Locking symfony/deprecation-contracts (v3.0.0)
11:21:25 AM:   - Locking symfony/filesystem (v6.0.0)
11:21:25 AM:   - Locking symfony/polyfill-ctype (v1.23.0)
11:21:25 AM:   - Locking symfony/polyfill-intl-grapheme (v1.23.1)
11:21:25 AM:   - Locking symfony/polyfill-intl-normalizer (v1.23.0)
11:21:25 AM:   - Locking symfony/polyfill-mbstring (v1.23.1)
11:21:25 AM:   - Locking symfony/polyfill-php72 (v1.23.0)
11:21:25 AM:   - Locking symfony/polyfill-php80 (v1.23.1)
11:21:25 AM:   - Locking symfony/polyfill-php81 (v1.23.0)
11:21:25 AM:   - Locking symfony/service-contracts (v3.0.0)
11:21:25 AM:   - Locking symfony/stopwatch (v6.0.0)
11:21:25 AM:   - Locking symfony/string (v6.0.0)
11:21:25 AM:   - Locking symfony/var-dumper (v4.4.34)
11:21:25 AM:   - Locking symfony/yaml (v6.0.0)
11:21:25 AM:   - Locking theseer/tokenizer (1.2.1)
11:21:25 AM:   - Locking vimeo/psalm (v4.15.0)
11:21:25 AM:   - Locking webmozart/assert (1.10.0)
11:21:25 AM:   - Locking webmozart/path-util (2.3.0)
11:21:25 AM: Writing lock file
11:21:25 AM: Installing dependencies from lock file (including require-dev)
11:21:25 AM: Package operations: 74 installs, 0 updates, 0 removals
11:21:25 AM:   - Downloading composer/package-versions-deprecated (1.11.99.4)
11:21:25 AM:   - Downloading composer/pcre (1.0.0)
11:21:25 AM:   - Downloading guzzlehttp/promises (1.5.1)
11:21:25 AM:   - Downloading ralouphie/getallheaders (3.0.3)
11:21:25 AM:   - Downloading psr/http-message (1.0.1)
11:21:25 AM:   - Downloading psr/http-factory (1.0.1)
11:21:25 AM:   - Downloading guzzlehttp/psr7 (2.1.0)
11:21:25 AM:   - Downloading psr/http-client (1.0.1)
11:21:25 AM:   - Downloading nimbly/capsule (1.1.2)
11:21:25 AM:   - Downloading nimbly/shuttle (0.4)
11:21:25 AM:   - Downloading symfony/polyfill-ctype (v1.23.0)
11:21:25 AM:   - Downloading symfony/yaml (v6.0.0)
11:21:25 AM:   - Downloading psr/container (2.0.2)
11:21:25 AM:   - Downloading symfony/service-contracts (v3.0.0)
11:21:25 AM:   - Downloading symfony/stopwatch (v6.0.0)
11:21:25 AM:   - Downloading symfony/polyfill-mbstring (v1.23.1)
11:21:25 AM:   - Downloading symfony/polyfill-intl-normalizer (v1.23.0)
11:21:25 AM:   - Downloading symfony/polyfill-intl-grapheme (v1.23.1)
11:21:25 AM:   - Downloading symfony/string (v6.0.0)
11:21:25 AM:   - Downloading symfony/console (v6.0.0)
11:21:25 AM:   - Downloading symfony/polyfill-php81 (v1.23.0)
11:21:25 AM:   - Downloading symfony/filesystem (v6.0.0)
11:21:25 AM:   - Downloading symfony/deprecation-contracts (v3.0.0)
11:21:25 AM:   - Downloading symfony/config (v6.0.0)
11:21:25 AM:   - Downloading psr/log (2.0.0)
11:21:25 AM:   - Downloading guzzlehttp/guzzle (7.4.1)
11:21:25 AM:   - Downloading php-coveralls/php-coveralls (v2.5.2)
11:21:25 AM:   - Downloading webmozart/assert (1.10.0)
11:21:25 AM:   - Downloading phpdocumentor/reflection-common (2.2.0)
11:21:25 AM:   - Downloading phpdocumentor/type-resolver (1.5.1)
11:21:25 AM:   - Downloading phpdocumentor/reflection-docblock (5.3.0)
11:21:25 AM:   - Downloading sebastian/version (3.0.2)
11:21:25 AM:   - Downloading sebastian/type (2.3.4)
11:21:25 AM:   - Downloading sebastian/resource-operations (3.0.3)
11:21:25 AM:   - Downloading sebastian/recursion-context (4.0.4)
11:21:25 AM:   - Downloading sebastian/object-reflector (2.0.4)
11:21:25 AM:   - Downloading sebastian/object-enumerator (4.0.4)
11:21:25 AM:   - Downloading sebastian/global-state (5.0.3)
11:21:25 AM:   - Downloading sebastian/exporter (4.0.4)
11:21:25 AM:   - Downloading sebastian/environment (5.1.3)
11:21:25 AM:   - Downloading sebastian/diff (4.0.4)
11:21:25 AM:   - Downloading sebastian/comparator (4.0.6)
11:21:25 AM:   - Downloading sebastian/code-unit (1.0.8)
11:21:25 AM:   - Downloading sebastian/cli-parser (1.0.1)
11:21:25 AM:   - Downloading phpunit/php-timer (5.0.3)
11:21:25 AM:   - Downloading phpunit/php-text-template (2.0.4)
11:21:25 AM:   - Downloading phpunit/php-invoker (3.1.1)
11:21:25 AM:   - Downloading phpunit/php-file-iterator (3.0.6)
11:21:25 AM:   - Downloading theseer/tokenizer (1.2.1)
11:21:25 AM:   - Downloading nikic/php-parser (v4.13.2)
11:21:25 AM:   - Downloading sebastian/lines-of-code (1.0.3)
11:21:25 AM:   - Downloading sebastian/complexity (2.0.2)
11:21:25 AM:   - Downloading sebastian/code-unit-reverse-lookup (2.0.3)
11:21:25 AM:   - Downloading phpunit/php-code-coverage (9.2.10)
11:21:25 AM:   - Downloading doctrine/instantiator (1.4.0)
11:21:25 AM:   - Downloading phpspec/prophecy (v1.15.0)
11:21:25 AM:   - Downloading phar-io/version (3.1.0)
11:21:25 AM:   - Downloading phar-io/manifest (2.0.3)
11:21:25 AM:   - Downloading myclabs/deep-copy (1.10.2)
11:21:25 AM:   - Downloading phpunit/phpunit (9.5.10)
11:21:25 AM:   - Downloading symfony/polyfill-php80 (v1.23.1)
11:21:25 AM:   - Downloading symfony/polyfill-php72 (v1.23.0)
11:21:25 AM:   - Downloading symfony/var-dumper (v4.4.34)
11:21:25 AM:   - Downloading webmozart/path-util (2.3.0)
11:21:25 AM:   - Downloading openlss/lib-array2xml (1.0.0)
11:21:25 AM:   - Downloading netresearch/jsonmapper (v4.0.0)
11:21:25 AM:   - Downloading felixfbecker/language-server-protocol (1.5.1)
11:21:25 AM:   - Downloading felixfbecker/advanced-json-rpc (v3.2.1)
11:21:25 AM:   - Downloading dnoegel/php-xdg-base-dir (v0.1.1)
11:21:25 AM:   - Downloading composer/xdebug-handler (2.0.3)
11:21:25 AM:   - Downloading composer/semver (3.2.6)
11:21:25 AM:   - Downloading amphp/amp (v2.6.1)
11:21:25 AM:   - Downloading amphp/byte-stream (v1.8.1)
11:21:25 AM:   - Downloading vimeo/psalm (v4.15.0)
11:21:26 AM:   - Installing composer/package-versions-deprecated (1.11.99.4): Extracting archive
11:21:26 AM:   - Installing composer/pcre (1.0.0): Extracting archive
11:21:26 AM:   - Installing guzzlehttp/promises (1.5.1): Extracting archive
11:21:26 AM:   - Installing ralouphie/getallheaders (3.0.3): Extracting archive
11:21:26 AM:   - Installing psr/http-message (1.0.1): Extracting archive
11:21:26 AM:   - Installing psr/http-factory (1.0.1): Extracting archive
11:21:26 AM:   - Installing guzzlehttp/psr7 (2.1.0): Extracting archive
11:21:26 AM:   - Installing psr/http-client (1.0.1): Extracting archive
11:21:26 AM:   - Installing nimbly/capsule (1.1.2): Extracting archive
11:21:26 AM:   - Installing nimbly/shuttle (0.4): Extracting archive
11:21:26 AM:   - Installing symfony/polyfill-ctype (v1.23.0): Extracting archive
11:21:26 AM:   - Installing symfony/yaml (v6.0.0): Extracting archive
11:21:26 AM:   - Installing psr/container (2.0.2): Extracting archive
11:21:26 AM:   - Installing symfony/service-contracts (v3.0.0): Extracting archive
11:21:26 AM:   - Installing symfony/stopwatch (v6.0.0): Extracting archive
11:21:26 AM:   - Installing symfony/polyfill-mbstring (v1.23.1): Extracting archive
11:21:26 AM:   - Installing symfony/polyfill-intl-normalizer (v1.23.0): Extracting archive
11:21:26 AM:   - Installing symfony/polyfill-intl-grapheme (v1.23.1): Extracting archive
11:21:26 AM:   - Installing symfony/string (v6.0.0): Extracting archive
11:21:26 AM:   - Installing symfony/console (v6.0.0): Extracting archive
11:21:26 AM:   - Installing symfony/polyfill-php81 (v1.23.0): Extracting archive
11:21:26 AM:   - Installing symfony/filesystem (v6.0.0): Extracting archive
11:21:26 AM:   - Installing symfony/deprecation-contracts (v3.0.0): Extracting archive
11:21:26 AM:   - Installing symfony/config (v6.0.0): Extracting archive
11:21:26 AM:   - Installing psr/log (2.0.0): Extracting archive
11:21:26 AM:   - Installing guzzlehttp/guzzle (7.4.1): Extracting archive
11:21:26 AM:   - Installing php-coveralls/php-coveralls (v2.5.2): Extracting archive
11:21:26 AM:   - Installing webmozart/assert (1.10.0): Extracting archive
11:21:26 AM:   - Installing phpdocumentor/reflection-common (2.2.0): Extracting archive
11:21:26 AM:   - Installing phpdocumentor/type-resolver (1.5.1): Extracting archive
11:21:26 AM:   - Installing phpdocumentor/reflection-docblock (5.3.0): Extracting archive
11:21:26 AM:   - Installing sebastian/version (3.0.2): Extracting archive
11:21:26 AM:   - Installing sebastian/type (2.3.4): Extracting archive
11:21:26 AM:   - Installing sebastian/resource-operations (3.0.3): Extracting archive
11:21:26 AM:   - Installing sebastian/recursion-context (4.0.4): Extracting archive
11:21:26 AM:   - Installing sebastian/object-reflector (2.0.4): Extracting archive
11:21:26 AM:   - Installing sebastian/object-enumerator (4.0.4): Extracting archive
11:21:26 AM:   - Installing sebastian/global-state (5.0.3): Extracting archive
11:21:26 AM:   - Installing sebastian/exporter (4.0.4): Extracting archive
11:21:26 AM:   - Installing sebastian/environment (5.1.3): Extracting archive
11:21:26 AM:   - Installing sebastian/diff (4.0.4): Extracting archive
11:21:26 AM:   - Installing sebastian/comparator (4.0.6): Extracting archive
11:21:26 AM:   - Installing sebastian/code-unit (1.0.8): Extracting archive
11:21:26 AM:   - Installing sebastian/cli-parser (1.0.1): Extracting archive
11:21:26 AM:   - Installing phpunit/php-timer (5.0.3): Extracting archive
11:21:26 AM:   - Installing phpunit/php-text-template (2.0.4): Extracting archive
11:21:26 AM:   - Installing phpunit/php-invoker (3.1.1): Extracting archive
11:21:26 AM:   - Installing phpunit/php-file-iterator (3.0.6): Extracting archive
11:21:26 AM:   - Installing theseer/tokenizer (1.2.1): Extracting archive
11:21:26 AM:   - Installing nikic/php-parser (v4.13.2): Extracting archive
11:21:26 AM:   - Installing sebastian/lines-of-code (1.0.3): Extracting archive
11:21:26 AM:   - Installing sebastian/complexity (2.0.2): Extracting archive
11:21:26 AM:   - Installing sebastian/code-unit-reverse-lookup (2.0.3): Extracting archive
11:21:26 AM:   - Installing phpunit/php-code-coverage (9.2.10): Extracting archive
11:21:26 AM:   - Installing doctrine/instantiator (1.4.0): Extracting archive
11:21:26 AM:   - Installing phpspec/prophecy (v1.15.0): Extracting archive
11:21:26 AM:   - Installing phar-io/version (3.1.0): Extracting archive
11:21:26 AM:   - Installing phar-io/manifest (2.0.3): Extracting archive
11:21:26 AM:   - Installing myclabs/deep-copy (1.10.2): Extracting archive
11:21:26 AM:   - Installing phpunit/phpunit (9.5.10): Extracting archive
11:21:26 AM:   - Installing symfony/polyfill-php80 (v1.23.1): Extracting archive
11:21:26 AM:   - Installing symfony/polyfill-php72 (v1.23.0): Extracting archive
11:21:26 AM:   - Installing symfony/var-dumper (v4.4.34): Extracting archive
11:21:26 AM:   - Installing webmozart/path-util (2.3.0): Extracting archive
11:21:26 AM:   - Installing openlss/lib-array2xml (1.0.0): Extracting archive
11:21:26 AM:   - Installing netresearch/jsonmapper (v4.0.0): Extracting archive
11:21:26 AM:   - Installing felixfbecker/language-server-protocol (1.5.1): Extracting archive
11:21:26 AM:   - Installing felixfbecker/advanced-json-rpc (v3.2.1): Extracting archive
11:21:26 AM:   - Installing dnoegel/php-xdg-base-dir (v0.1.1): Extracting archive
11:21:26 AM:   - Installing composer/xdebug-handler (2.0.3): Extracting archive
11:21:26 AM:   - Installing composer/semver (3.2.6): Extracting archive
11:21:26 AM:   - Installing amphp/amp (v2.6.1): Extracting archive
11:21:26 AM:   - Installing amphp/byte-stream (v1.8.1): Extracting archive
11:21:26 AM:   - Installing vimeo/psalm (v4.15.0): Extracting archive
11:21:28 AM: 12 package suggestions were added by new dependencies, use `composer suggest` to see details.
11:21:28 AM: Package webmozart/path-util is abandoned, you should avoid using it. Use symfony/filesystem instead.
11:21:28 AM: Generating autoload files
11:21:28 AM: composer/package-versions-deprecated: Generating version class...
11:21:28 AM: composer/package-versions-deprecated: ...done generating version class
11:21:28 AM: 50 packages you are using are looking for funding.
11:21:28 AM: Use the `composer fund` command to find out more!
11:21:28 AM: Started restoring cached go cache
11:21:28 AM: Finished restoring cached go cache
11:21:28 AM: go version go1.16.5 linux/amd64
11:21:28 AM: go version go1.16.5 linux/amd64
11:21:28 AM: Installing missing commands
11:21:28 AM: Verify run directory
11:21:30 AM: ​
11:21:30 AM: ────────────────────────────────────────────────────────────────
11:21:30 AM:   Netlify Build                                                 
11:21:30 AM: ────────────────────────────────────────────────────────────────
11:21:30 AM: ​
11:21:30 AM: ❯ Version
11:21:30 AM:   @netlify/build 20.1.0
11:21:30 AM: ​
11:21:30 AM: ❯ Flags
11:21:30 AM:   baseRelDir: true
11:21:30 AM:   buildId: 61b1e6a360f8ea00084e82b3
11:21:30 AM:   deployId: 61b1e6a360f8ea00084e82b5
11:21:30 AM: ​
11:21:30 AM: ❯ Current directory
11:21:30 AM:   /opt/build/repo
11:21:30 AM: ​
11:21:30 AM: ❯ Config file
11:21:30 AM:   /opt/build/repo/netlify.toml
11:21:30 AM: ​
11:21:30 AM: ❯ Context
11:21:30 AM:   production
11:21:31 AM: ​
11:21:31 AM: ❯ Installing plugins
11:21:31 AM:    - netlify-purge-cloudflare-on-deploy@1.2.0
11:21:31 AM:    - netlify-plugin-html-validate@1.0.0
11:21:31 AM:    - netlify-plugin-use-env-in-runtime@1.2.1
11:21:31 AM:    - netlify-plugin-jekyll-cache@1.0.0
11:21:37 AM: ​
11:21:37 AM: ❯ Loading plugins
11:21:37 AM:    - netlify-purge-cloudflare-on-deploy@1.2.0 from Netlify app
11:21:37 AM:    - netlify-plugin-html-validate@1.0.0 from Netlify app
11:21:37 AM:    - netlify-plugin-use-env-in-runtime@1.2.1 from Netlify app
11:21:37 AM:    - netlify-plugin-jekyll-cache@1.0.0 from netlify.toml
11:21:38 AM: ​
11:21:38 AM: ────────────────────────────────────────────────────────────────
11:21:38 AM:   1. netlify-plugin-use-env-in-runtime (onPreBuild event)       
11:21:38 AM: ────────────────────────────────────────────────────────────────
11:21:38 AM: ​
11:21:38 AM: Starting the "uefn" plugin process
11:21:38 AM:   No "prefix" input defined. Skip the process.
11:21:38 AM: ​
11:21:38 AM: (netlify-plugin-use-env-in-runtime onPreBuild completed in 16ms)
11:21:38 AM: ​
11:21:38 AM: ────────────────────────────────────────────────────────────────
11:21:38 AM:   2. netlify-plugin-jekyll-cache (onPreBuild event)             
11:21:38 AM: ────────────────────────────────────────────────────────────────
11:21:38 AM: ​
11:21:38 AM: ​
11:21:38 AM: ────────────────────────────────────────────────────────────────
11:21:38 AM:   Plugin "netlify-plugin-jekyll-cache" internal error           
11:21:38 AM: ────────────────────────────────────────────────────────────────
11:21:38 AM: ​
11:21:38 AM:   Error message
11:21:38 AM:   Error: Cannot cache /opt/build/repo because it is the current directory (/opt/build/repo) or a parent directory
11:21:38 AM: ​
11:21:38 AM:   Plugin details
11:21:38 AM:   Package:        netlify-plugin-jekyll-cache
11:21:38 AM:   Version:        1.0.0
11:21:38 AM:   Repository:     git+https://github.com/Mesomorphic/netlify-plugin-jekyll-cache.git
11:21:38 AM:   npm link:       https://www.npmjs.com/package/netlify-plugin-jekyll-cache
11:21:38 AM:   Report issues:  https://github.com/Mesomorphic/netlify-plugin-jekyll-cache/issues
11:21:38 AM: ​
11:21:38 AM:   Error location
11:21:38 AM:   In "onPreBuild" event in "netlify-plugin-jekyll-cache" from netlify.toml
11:21:38 AM:       at checkSrcPath (/opt/buildhome/node-deps/node_modules/@netlify/cache-utils/src/path.js:46:11)
11:21:38 AM:       at getSrcPath (/opt/buildhome/node-deps/node_modules/@netlify/cache-utils/src/path.js:20:3)
11:21:38 AM:       at async parsePath (/opt/buildhome/node-deps/node_modules/@netlify/cache-utils/src/path.js:11:19)
11:21:38 AM:       at async restoreOne (/opt/buildhome/node-deps/node_modules/@netlify/cache-utils/src/main.js:36:34)
11:21:38 AM:       at async Promise.all (index 0)
11:21:38 AM:       at async allowMany (/opt/buildhome/node-deps/node_modules/@netlify/cache-utils/src/main.js:83:19)
11:21:38 AM:       at async onPreBuild (/opt/build/repo/.netlify/plugins/node_modules/netlify-plugin-jekyll-cache/index.js:8:9)
11:21:38 AM:       at async Object.run (/opt/buildhome/node-deps/node_modules/@netlify/build/src/plugins/child/run.js:17:3)
11:21:38 AM:       at async handleEvent (/opt/buildhome/node-deps/node_modules/@netlify/build/src/plugins/child/main.js:34:38)
11:21:38 AM:       at async process.<anonymous> (/opt/buildhome/node-deps/node_modules/@netlify/build/src/plugins/ipc.js:103:16)
11:21:38 AM: ​
11:21:38 AM:   Resolved config
11:21:38 AM:   build:
11:21:38 AM:     command: npm run jekyll build
11:21:38 AM:     commandOrigin: ui
11:21:38 AM:     publish: /opt/build/repo
11:21:38 AM:     publishOrigin: default
11:21:38 AM:   functionsDirectory: /opt/build/repo/blackstarvirtualmint
11:21:38 AM:   plugins:
11:21:38 AM:     - inputs: {}
11:21:38 AM:       origin: ui
11:21:38 AM:       package: netlify-purge-cloudflare-on-deploy
11:21:38 AM:     - inputs: {}
11:21:38 AM:       origin: ui
11:21:38 AM:       package: netlify-plugin-html-validate
11:21:38 AM:     - inputs: {}
11:21:38 AM:       origin: ui
11:21:38 AM:       package: netlify-plugin-use-env-in-runtime
11:21:38 AM:     - inputs: {}
11:21:38 AM:       origin: config
11:21:38 AM:       package: netlify-plugin-jekyll-cache
11:21:39 AM: Caching artifacts
11:21:39 AM: Started saving node modules
11:21:39 AM: Finished saving node modules
11:21:39 AM: Started saving build plugins
11:21:39 AM: Finished saving build plugins
11:21:39 AM: Started saving pip cache
11:21:39 AM: Finished saving pip cache
11:21:39 AM: Started saving emacs cask dependencies
11:21:39 AM: Finished saving emacs cask dependencies
11:21:39 AM: Started saving maven dependencies
11:21:39 AM: Finished saving maven dependencies
11:21:39 AM: Started saving boot dependencies
11:21:39 AM: Finished saving boot dependencies
11:21:39 AM: Started saving composer dependencies
11:21:39 AM: Finished saving composer dependencies
11:21:39 AM: Started saving rust rustup cache
11:21:39 AM: Finished saving rust rustup cache
11:21:39 AM: Started saving go dependencies
11:21:39 AM: Finished saving go dependencies
11:21:42 AM: Build failed due to a plugin error: Build script returned non-zero exit code: 3
11:21:42 AM: Creating deploy upload records
11:21:42 AM: Failing build: Failed to build site
11:21:42 AM: Failed during stage 'building site': Build script returned non-zero exit code: 3
11:21:42 AM: Finished processing build request in 32.926584619s please assist

**Comment by typhoon2099** [comment]
@Agadelic Is this a Jekyll project? You mentioned Gatsby, which if you're using then you'd need to use something like https://github.com/netlify/netlify-plugin-gatsby
